name: Telegram Download and Upload

on:
  workflow_dispatch:
    inputs:
      telegram_link:
        description: 'Telegram LINK to download'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests telethon

      - name: Run script
        env:
          TELEGRAM_LINK: ${{ inputs.telegram_link }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IUTBOX_USERNAME: ${{ secrets.IUTBOX_USER }}
          IUTBOX_PASSWORD: ${{ secrets.IUTBOX_PASS }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
        run: python telegram.py
